// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oobcjgowqmrnjzsvybbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vYmNqZ293cW1ybmp6c3Z5YmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxNDI2NTMsImV4cCI6MjA4OTcxODY1M30.lsx8rs9CGDbkIVdEPi4LH9E8w2-3oMCupPSo9VtcRtw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});